# Generated by Django 3.2 on 2021-05-16 13:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('homepage', models.CharField(max_length=256)),
                ('crawl_type', models.CharField(choices=[('all', 'All'), ('latest', 'Latest')], default='latest', max_length=50)),
                ('scheduler_type', models.CharField(choices=[('once', 'Once'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='once', max_length=50)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('job_id', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256, verbose_name='URL')),
                ('is_multiple', models.BooleanField(verbose_name='Multiple')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperSpider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.scraper')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.spider')),
            ],
        ),
        migrations.AddField(
            model_name='scraper',
            name='spiders',
            field=models.ManyToManyField(through='news.ScraperSpider', to='news.Spider'),
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('selector_type', models.CharField(choices=[('xpath', 'XPATH'), ('css', 'CSS')], default='xpath', max_length=50)),
                ('selector', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.spider')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(null=True)),
                ('url', models.CharField(max_length=256)),
                ('thumbnail_link', models.CharField(max_length=256, null=True)),
                ('image_link', models.CharField(max_length=256, null=True)),
                ('author', models.CharField(max_length=256)),
                ('summary', models.TextField(null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='news.Category')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('url', models.TextField()),
                ('author', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('published_at', models.TextField(null=True)),
                ('thumbnail_link', models.TextField(null=True)),
                ('image_link', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.spider')),
            ],
        ),
    ]
